2025-10-18 06:23:32,682 (33775/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-10-18 06:23:32,682 (33775/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-10-18 06:23:51,331 (34234/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-10-18 06:23:51,331 (34234/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-10-18 06:23:51,398 (34234/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/main.py", line 766, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/main.py", line 737, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/psycopg/connection.py", line 120, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "severntrent" does not exist\n'
2025-10-18 06:23:55,102 (34293/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-10-18 06:23:55,102 (34293/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-10-18 06:23:55,153 (34293/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/main.py", line 766, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/main.py", line 737, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/psycopg/connection.py", line 120, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "st" does not exist\n'
2025-10-18 06:24:17,710 (35400/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-10-18 06:24:17,710 (35400/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-10-18 06:24:17,759 (35400/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/main.py", line 766, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/main.py", line 737, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.14/site-packages/psycopg/connection.py", line 120, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "pwl" does not exist\n'
